wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1632241599
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 16
      4: 3.6.9
      5: 0.12.2
      8:
      - 5
adjust_lr_every:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 1
checkpoint_path:
  desc: null
  value: /root/konst/model_checkpoints/ner_employment
data_path:
  desc: null
  value: /root/konst/data/nerus_lenta/nerus_lenta.conllu.gz
epochs:
  desc: null
  value: 20
factor:
  desc: null
  value: 0.5
lam:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.001
model_path:
  desc: null
  value: ''
num_workers:
  desc: null
  value: 1
patience:
  desc: null
  value: 2
save_at:
  desc: null
  value: 1
start_epoch:
  desc: null
  value: 0
use_wandb:
  desc: null
  value: true
