wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1636474753
    t:
      1:
      - 1
      - 5
      4: 3.6.9
      5: 0.12.0
      8:
      - 5
adjust_lr_every:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 128
checkpoint_path:
  desc: null
  value: /root/konst/model_checkpoints/toxic_deep
data_path:
  desc: null
  value: /root/konst/data/toxic_bio/toxic_bio_dataset.csv
epochs:
  desc: null
  value: 100
factor:
  desc: null
  value: 0.5
lam:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.001
model_path:
  desc: null
  value: toxic_epoch_12_acc_0.8393_vs_0.0564_loss_0.2697_vs_0.7157.pth
num_workers:
  desc: null
  value: 0
patience:
  desc: null
  value: 5
save_at:
  desc: null
  value: 1
start_epoch:
  desc: null
  value: 0
test_size:
  desc: null
  value: 0.2
use_wandb:
  desc: null
  value: true
